### ISSUE TITLE
More intelligent RubyMotion file detection

### ISSUE THREAD

**Issue by satococoa** [satococoa/atom-rubymotion#1]
Now, firstLineMatch is used to detect RubyMotion file detection.

https://github.com/satococoa/atom-rubymotion/blob/master/grammars/rubymotion.cson#L2

It may be better to set project-wide setting not only look into the first line.

**Comment by markrickert** [comment]
I'd say look at the `Rakefile` and detect `"/Library/RubyMotion/lib"` from the project level.

Every RubyMotion `Rakefile` must have the line:

``` ruby
$:.unshift("/Library/RubyMotion/lib")
```

**Comment by satococoa** [comment]
I don't know how to set syntax **project-wide** though, It's a good idea, thank you.

SublimeRubyMotionBuilder's detection logic is almost same.

https://github.com/RubyMotionJP/SublimeRubyMotionBuilder/blob/master/RubyMotionBuilder.py#L17
