### ISSUE TITLE
Convert already written snippets to work with this package

### ISSUE THREAD

**Issue by ahmetabdi** [satococoa/atom-rubymotion#2]
https://github.com/rcyrus/snipmate-snippets-rubymotion/blob/master/snippets/rubymotion.snippets

**Comment by satococoa** [comment]
Converting this file or generating snippets from *.bridgesupport / ctags is not difficult,
but Atom (autocomplete package) does not support autocomplete from snippets currently.

So just adding snippets does not make our coding easy.

We must implement autocomplete and snippts in other way.
(For example, making another autocomplete package or adding snippets support to autocomplete, ...etc.)
My plan is extending https://github.com/atom/autocomplete package.

Anyway, thank you for your comment.

**Comment by satococoa** [comment]
> So just adding snippets does not make our coding easy.

This means, 
- If you want to get `tableView(${1}, numberOfRowsInSection: ${2})${3}`,
- You must type `tableView:numberOfRowsInSection:<TAB>`.

I want to use sublime text style autocomplete and snippets.

(Described below, snippets are listed in autocomplete list
http://www.hongkiat.com/blog/sublime-code-snippets/)

**Comment by ahmetabdi** [comment]
Ah I get it, might take awhile to get them all in.. wonder if there is an automated way somehow

**Comment by satococoa** [comment]
#3
